"""users table

Revision ID: 17bbb3c76a6b
Revises: 799dad6a53dd
Create Date: 2019-05-13 15:10:53.084078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17bbb3c76a6b'
down_revision = '799dad6a53dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cat', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_cat'), 'user', ['cat'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_cat'), table_name='user')
    op.drop_column('user', 'cat')
    # ### end Alembic commands ###
